# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appArbitro', '0003_alter_arbitro_pais_id_alter_detalle_terma_arbitro_id_and_more'),
        ('appEquipo', '0003_alter_alineacion_equipo_contrato_id_and_more'),
        ('appCompeticion', '0003_alter_competicion_tipo_competicion_id_and_more'),
        ('appContrato', '0002_alter_contrato_persona_id_alter_persona_pais_id_and_more'),
        ('appPartido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='equipo_local_id',
            field=models.ForeignKey(db_column='equipo_local_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local_id', to='appEquipo.equipo'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='equipo_visitante_id',
            field=models.ForeignKey(db_column='equipo_visitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante_id', to='appEquipo.equipo'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='sede_id',
            field=models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.sede'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='terma_arbitral_id',
            field=models.ForeignKey(db_column='terma_arbitral_id', on_delete=django.db.models.deletion.CASCADE, to='appArbitro.terma_arbitral'),
        ),
        migrations.AlterField(
            model_name='evento_persona',
            name='encuentro_id',
            field=models.ForeignKey(db_column='encuentro_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro'),
        ),
        migrations.AlterField(
            model_name='evento_persona',
            name='evento_id',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.evento'),
        ),
        migrations.AlterField(
            model_name='evento_persona',
            name='persona_id',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.persona'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad_id',
            field=models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.ciudad'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estado_id',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.estado'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='pais_id',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais'),
        ),
    ]
