# Generated by Django 4.1.1 on 2022-09-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0002_alter_encuentro_equipo_local_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'ciudad'},
        ),
        migrations.AlterModelOptions(
            name='encuentro',
            options={'verbose_name_plural': 'encuentro'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': 'estado'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'evento'},
        ),
        migrations.AlterModelOptions(
            name='evento_persona',
            options={'verbose_name_plural': 'evento_persona'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'sede'},
        ),
    ]
