# Generated by Django 4.1.1 on 2022-09-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arbitro',
            fields=[
                ('arbitro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_arbitro', models.CharField(max_length=1)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='terma_arbitral',
            fields=[
                ('terma_arbitral_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='detalle_terma',
            fields=[
                ('detalle_terma_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_jugo', models.BooleanField()),
                ('arbitro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appArbitro.arbitro')),
                ('terma_arbitral_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appArbitro.terma_arbitral')),
            ],
        ),
    ]
