# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0002_initial'),
        ('appArbitro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='pais_id',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais'),
        ),
        migrations.AlterField(
            model_name='detalle_terma',
            name='arbitro_id',
            field=models.ForeignKey(db_column='arbitro_id', on_delete=django.db.models.deletion.CASCADE, to='appArbitro.arbitro'),
        ),
        migrations.AlterField(
            model_name='detalle_terma',
            name='terma_arbitral_id',
            field=models.ForeignKey(db_column='tema_arbitral_id', on_delete=django.db.models.deletion.CASCADE, to='appArbitro.terma_arbitral'),
        ),
    ]
