# Generated by Django 4.1.1 on 2022-09-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appArbitro', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_terna',
            fields=[
                ('tipo_terna_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'tipo_terna',
            },
        ),
        migrations.AddField(
            model_name='detalle_terna',
            name='tipo_terna_id',
            field=models.ForeignKey(db_column='tipo_terna_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appArbitro.tipo_terna'),
            preserve_default=False,
        ),
    ]
