# Generated by Django 4.1.1 on 2022-09-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appArbitro', '0003_alter_arbitro_pais_id_alter_detalle_terma_arbitro_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitro',
            options={'verbose_name_plural': 'arbitro'},
        ),
        migrations.AlterModelOptions(
            name='detalle_terma',
            options={'verbose_name_plural': 'detalle_terma'},
        ),
        migrations.AlterModelOptions(
            name='terma_arbitral',
            options={'verbose_name_plural': 'terma_arbitral'},
        ),
    ]
