# Generated by Django 4.1.1 on 2022-09-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appArbitro', '0004_alter_arbitro_options_alter_detalle_terma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terma_arbitral',
            name='nombre_terma',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
