# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0003_alter_competicion_tipo_competicion_id_and_more'),
        ('appContrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='persona_id',
            field=models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais_id',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona_id',
            field=models.ForeignKey(db_column='tipo_persona_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.tipo_persona'),
        ),
    ]
