# Generated by Django 4.1.1 on 2022-09-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0001_initial'),
        ('appContrato', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='pais_id',
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad_id',
            field=models.ForeignKey(db_column='ciudad_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appPartido.ciudad'),
            preserve_default=False,
        ),
    ]
