# Generated by Django 4.1.1 on 2022-09-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCompeticion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alineacion_equipo',
            fields=[
                ('alineacion_equipo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dorsal', models.IntegerField()),
                ('capitan', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='posicion_jugador',
            fields=[
                ('posicion_jugador_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_equipo',
            fields=[
                ('tipo_equipo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('equipo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo', models.BinaryField()),
                ('vestimenta', models.BinaryField()),
                ('nombre', models.CharField(max_length=70)),
                ('siglas', models.CharField(max_length=3)),
                ('deporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.deporte')),
            ],
        ),
    ]
