# Generated by Django 4.1.1 on 2022-09-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0002_alter_contrato_persona_id_alter_persona_pais_id_and_more'),
        ('appCompeticion', '0003_alter_competicion_tipo_competicion_id_and_more'),
        ('appPartido', '0001_initial'),
        ('appEquipo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacion_equipo',
            name='contrato_id',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato'),
        ),
        migrations.AlterField(
            model_name='alineacion_equipo',
            name='equipo_id',
            field=models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, to='appEquipo.equipo'),
        ),
        migrations.AlterField(
            model_name='alineacion_equipo',
            name='posicion_jugador_id',
            field=models.ForeignKey(db_column='posicion_jugador_id', on_delete=django.db.models.deletion.CASCADE, to='appEquipo.posicion_jugador'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='deporte_id',
            field=models.ForeignKey(db_column='deporte_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.deporte'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='encuentro_id',
            field=models.ForeignKey(db_column='encuentro_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sede_id',
            field=models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.sede'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo_id',
            field=models.ForeignKey(db_column='tipo_equipo_id', on_delete=django.db.models.deletion.CASCADE, to='appEquipo.tipo_equipo'),
        ),
    ]
