# Generated by Django 4.1.1 on 2022-09-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0003_alter_alineacion_equipo_contrato_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alineacion_equipo',
            options={'verbose_name_plural': 'alineacion_equipo'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': 'equipo'},
        ),
        migrations.AlterModelOptions(
            name='posicion_jugador',
            options={'verbose_name_plural': 'posicion_jugador'},
        ),
        migrations.AlterModelOptions(
            name='tipo_equipo',
            options={'verbose_name_plural': 'tipo_equipo'},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='encuentro_id',
        ),
    ]
