# Generated by Django 4.1.1 on 2022-09-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0004_alter_alineacion_equipo_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/equipo/logo/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='vestimenta',
            field=models.ImageField(blank=True, null=True, upload_to='media/equipo/vestimenta/'),
        ),
    ]
