# Generated by Django 4.1.1 on 2022-09-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0005_alter_equipo_logo_alter_equipo_vestimenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/logo/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='vestimenta',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta/'),
        ),
    ]
