# Generated by Django 4.1.1 on 2022-09-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0003_alter_competicion_tipo_competicion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competicion',
            options={'verbose_name_plural': 'competicion'},
        ),
        migrations.AlterModelOptions(
            name='deporte',
            options={'verbose_name_plural': 'deporte'},
        ),
        migrations.AlterModelOptions(
            name='detalle_grupo',
            options={'verbose_name_plural': 'detalle_grupo'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name_plural': 'grupo'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'pais'},
        ),
        migrations.AlterModelOptions(
            name='tabla',
            options={'verbose_name_plural': 'tabla'},
        ),
        migrations.AlterModelOptions(
            name='tipo_competicion',
            options={'verbose_name_plural': 'tipo_competicion'},
        ),
    ]
